<?php

namespace App\Http\Controllers;

use App\Models\PasswordReset;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PublicController extends Controller
{
    public function index()
    {
        return view('index');
    } // index


    public function register()
    {
        return view('register');
    } // register 


    public function login()
    {
        // $old = [
        //     'cp@example.com',
        //     'tgp@example.com',
        //     'vvp@example.com',
        //     'guu@example.com',
        //     'ru@example.com',
        //     'aspy@example.com',
        //     'asum@example.com',
        //     'asua@example.com',
        //     'nau@example.com',
        //     'tftfp@example.com',
        //     'noouoe@example.com',
        //     'ttu@example.com',
        //     'muo@example.com',
        //     'spu@example.com',
        //     'uou@example.com',
        //     'man@example.com',
        //     'aisu@example.com',
        //     'ou@example.com',
        //     'ap@example.com',
        //     'hpe@example.com',
        //     'snyueeioe@example.com',
        //     'aiscoea@example.com',
        //     'sobs@example.com',
        //     'cns@example.com',
        //     'coa@example.com',
        //     'noub@example.com',
        //     'bscot@example.com',
        //     'fpe@example.com',
        //     'fgb@example.com',
        //     'ffdt@example.com',
        //     'fh@example.com',
        //     'ftc@example.com',
        //     'gst@example.com',
        //     'ftcis@example.com',
        //     'fet@example.com',
        //     'fco@example.com',
        //     'madonna@example.com',
        //     'ssp@example.com',
        //     'uou@example.com',
        //     'man@example.com',
        //     'atbu@example.com',
        //     'fpb@example.com',
        //     'fgc@example.com',
        //     'lys@example.com',
        //     'coea@example.com',
        //     'nou@example.com',
        //     'bscht@example.com',
        //     'fpe@example.com',
        //     'fuo@example.com',
        //     'isty@example.com',
        //     'ftcm@example.com',
        //     'fum@example.com',
        //     'muom@example.com',
        //     'noun@example.com',
        //     'rpm@example.com',
        //     'shtm@example.com',
        //     'sonm@example.com',
        //     'uoc@example.com',
        //     'crsuoc@example.com',
        //     'ibcao@example.com',
        //     'crscoe@example.com',
        //     'chti@example.com',
        //     'tcu@example.com',
        //     'fupre@example.com',
        //     'dsu@example.com',
        //     'dspo@example.com',
        //     'dspt@example.com',
        //     'dspp@example.com',
        //     'coea@example.com',
        //     'coew@example.com',
        //     'fceta@example.com',
        //     'cpem@example.com',
        //     'shtu@example.com',
        //     'pti@example.com',
        //     'wdu@example.com',
        //     'nuo@example.com',
        //     'nounc@example.com',
        //     'dsmtech@example.com',
        //     'nmuo@example.com',
        //     'csmtt@example.com',
        //     'uoict@example.com',
        //     'ssm@example.com',
        //     'sona@example.com',
        //     'sonw@example.com',
        //     'bson@example.com',
        //     'eku@example.com',
        //     'kehu@example.com',
        //     'wnn@example.com',
        //     'snnsca@example.com',
        //     'sonwb@example.com',
        //     'ebsu@example.com',
        //     'funai@example.com',
        //     'ebscoe@example.com',
        //     'aifu@example.com',
        //     'chs@example.com',
        //     'efc@example.com',
        //     'enscoet@example.com',
        //     'imt@example.com',
        //     'fcco@example.com',
        //     'escoe@example.com',
        //     'cuan@example.com',
        //     'rgu@example.com',
        //     'fsdtt@example.com',
        //     'cic@example.com',
        //     'osist@example.com',
        //     'tfcoe@example.com',
        //     'cu@example.com',
        //     'icea@example.com',
        //     'mili@example.com',
        //     'nicps@example.com',
        //     'sau@example.com',
        //     'aau@example.com',
        //     'uben@example.com',
        //     'bsue@example.com',
        //     'btc@example.com',
        //     'biu@example.com',
        //     'coeben@example.com',
        //     'esitm@example.com',
        //     'fpauchi@example.com',
        //     'igb@example.com',
        //     'lp@example.com',
        //     'noun@example.com',
        //     'sas@example.com',
        //     'sp@example.com',
        //     'ssnsapele@example.com',
        //     'usen@example.com',
        //     'wu@example.com',
        //     'wobc@example.com',
        //     'abu@example.com',
        //     'coeikere@example.com',
        //     'cpa@example.com',
        //     'dttc@example.com',
        //     'fpa@example.com',
        //     'fuoye@example.com',
        //     'gtc@example.com',
        //     'hmc@example.com',
        //     'son@example.com',
        //     'uad@example.com',
        //     'uosit@example.com',
        //     'cabs@example.com',
        //     'fuk@example.com',
        //     'fcetg@example.com',
        //     'gsu@example.com',
        //     'noun@example.com',
        //     'cip@example.com',
        //     'aist@example.com',
        //     'alv@example.com',
        //     'cbls@example.com',
        //     'chst@example.com',
        //     'fpnekede@example.com',
        //     'futo@example.com',
        //     'imopoly@example.com',
        //     'istai@example.com',
        //     'imsu@example.com',
        //     'nhrin@example.com',
        //     'noun@example.com',
        //     'nursing@example.com',
        //     'wofbi@example.com',
        //     'fedutse@example.com',
        //     'hafpk@example.com',
        //     'iiot@example.com',
        //     'jscag@example.com',
        //     'jscoe@example.com',
        //     'jspoly@example.com',
        //     'nti@example.com',
        //     'abu@example.com',
        //     'afit@example.com',
        //     'asics@example.com',
        //     'ascas@example.com',
        //     'bcts@example.com',
        //     'dci@example.com',
        //     'cik@example.com',
        //     'ffk@example.com',
        //     'fcfm@example.com',
        //     'fcc@example.com',
        //     'fss@example.com',
        //     'ftc@example.com',
        //     'gciz@example.com',
        //     'iit@example.com',
        //     'kadpoly@example.com',
        //     'kscoe@example.com',
        //     'kasu@example.com',
        //     'nok@example.com',
        //     'ncat@example.com',
        //     'nda@example.com',
        //     'nilst@example.com',
        //     'nbpz@example.com',
        //     'shtmak@example.com',
        //     'stgerards@example.com',
        //     'stluke@example.com',
        //     'fcclt@example.com',
        //     'zarfcoe@example.com',
        //     'srcoe@example.com',
        //     'akcoils@example.com',
        //     'bayu@example.com',
        //     'bctc@example.com',
        //     'cass@example.com',
        //     'cti@example.com',
        //     'fcetb@example.com',
        //     'kanfcoe@example.com',
        //     'ksp@example.com',
        //     'kingsglory@example.com',
        //     'kut@example.com',
        //     'npa@example.com',
        //     'sht@example.com',
        //     'fcekatsina@example.com',
        //     'fudutsinma@example.com',
        //     'hukp@example.com',
        //     'ikcedutsinma@example.com',
        //     'noun@example.com',
        //     'sbrsfuntua@example.com',
        //     'shtdaura@example.com',
        //     'shtkankia@example.com',
        //     'sommalumfashi@example.com',
        //     'sonkatsina@example.com',
        //     'umyu@example.com',
        //     'ybucollege@example.com',
        //     'aacoeargungu@example.com',
        //     'kus@example.com',
        //     'wufp@example.com',
        //     'ecwason@example.com',
        //     'fceokene@example.com',
        //     'fulokoja@example.com',
        //     'kscoe@example.com',
        //     'kscon@example.com',
        //     'ksp@example.com',
        //     'ksu@example.com',
        //     'noun@example.com',
        //     'sul@example.com',
        //     'fpidah@example.com',
        //     'collegeofnursing@example.com',
        //     'fpo@example.com',
        //     'alhikmah@example.com',
        //     'uil@example.com',
        //     'kscails@example.com',
        //     'kscoe@example.com',
        //     'kscht@example.com',
        //     'ksp@example.com',
        //     'kwasu@example.com',
        //     'landmark@example.com',
        //     'noun@example.com',
        //     'cibn@example.com',
        //     'cisn@example.com',
        //     'ican@example.com',
        //     'ismn@example.com',
        //     'lasotat@example.com',
        //     'lbs@example.com',
        //     'nipr@example.com',
        //     'nitt@example.com',
        //     'noic@example.com',
        //     'aocoe@example.com',
        //     'asconbadagry@example.com',
        //     'aeroland@example.com',
        //     'ama@example.com',
        //     'ameccollege@example.com',
        //     'aptech@example.com',
        //     'anan@example.com',
        //     'bellstechbadagry@example.com',
        //     'cia@example.com',
        //     'cimn@example.com',
        //     'cipsm@example.com',
        //     'cams@example.com',
        //     'cdssojo@example.com',
        //     'caleb@example.com',
        //     'dalewaresit@example.com',
        //     'excelcollege@example.com',
        //     'ezekielcollege@example.com',
        //     'fce@example.com',
        //     'fcetechakoka@example.com',
        //     'fcfmt@example.com',
        //     'fcoot@example.com',
        //     'fssvi@example.com',
        //     'fsot@example.com',
        //     'fedsciofscience@example.com',
        //     'fstc@example.com',
        //     'ftcikoyi@example.com',
        //     'ficinstitute@example.com',
        //     'goetheinstitut@example.com',
        //     'gtciadosoba@example.com',
        //     'gtcikorodu@example.com',
        //     'grano@example.com',
        //     'hicindustrialtech@example.com',
        //     'icen@example.com',
        //     'idpm@example.com',
        //     'ipakodogrammarschool@example.com',
        //     'karrox@example.com',
        //     'kbcibeshe@example.com',
        //     'laguniversity@example.com',
        //     'lcc@example.com',
        //     'lschtyaba@example.com',
        //     'lsp@example.com',
        //     'luth@example.com',
        //     'lifetheologicalseminary@example.com',
        //     'logosinstitute@example.com',
        //     'lsu@example.com',
        //     'miiit@example.com',
        //     'mocopmedu@example.com',
        //     'noun@example.com',
        //     'newhorizons@example.com',
        //     'nasfa@example.com',
        //     'nassm@example.com',
        //     'nasonm@example.com',
        //     'nijnim@example.com',
        //     'nispik@example.com',
        //     'nls@example.com',
        //     'niitnii@example.com',
        //     'pfdmion@example.com',
        //     'ruropin@example.com',
        //     'sfcak@example.com',
        //     'ystii@example.com',
        //     'tjiis@example.com',
        //     'wpx@example.com',
        //     'yabycot@example.com',
        //     'yicahm@example.com',
        //     'buek@example.com',
        //     'bgunuk@example.com',
        //     'futl@example.com',
        //     'nouon@example.com',
        //     'nsuke@example.com',
        //     'coea@example.com',
        //     'coal@example.com',
        //     'fedpolyn@example.com',
        //     'npak@example.com',
        //     'nsp@example.com',
        //     'fut@example.com',
        //     'minfut@example.com',
        //     'nouon@example.com',
        //     'fpb@example.com',
        //     'nsp@example.com',
        //     'cabs@example.com',
        //     'cemm@example.com',
        //     'colags@example.com',
        //     'coails@example.com',
        //     'fcek@example.com',
        //     'fcwmnb@example.com',
        //     'nscn@example.com',
        //     'sbtc@example.com',
        //     'buir@example.com',
        //     'bu@example.com',
        //     'but@example.com',
        //     'crau@example.com',
        //     'cu@example.com',
        //     'nouon@example.com',
        //     'oouoa@example.com',
        //     'uaao@example.com',
        //     'aap@example.com',
        //     'acp@example.com',
        //     'dsaipe@example.com',
        //     'fpi@example.com',
        //     'gp@example.com',
        //     'mapo@example.com',
        //     'tgp@example.com',
        //     'fcea@example.com',
        //     'icmt@example.com',
        //     'oscht@example.com',
        //     'scaad@example.com',
        //     'taiscoe@example.com',
        //     'yccoe@example.com',
        //     'zacais@example.com',
        //     'aau@example.com',
        //     'futa@example.com',
        //     'rgp@example.com',
        //     'au@example.com',
        //     'umso@example.com',
        //     'osustech@example.com',
        //     'wust@example.com',
        //     'eu@example.com',
        //     'aceo@example.com',
        //     'adeuniv@example.com',
        //     'bui@example.com',
        //     'cuif@example.com',
        //     'fuf@example.com',
        //     'fpee@example.com',
        //     'ip@example.com',
        //     'ospi@example.com',
        //     'tpi@example.com',
        //     'oscte@example.com',
        //     'ucti@example.com',
        //     'casi@example.com',
        //     'oscei@example.com',
        //     'oscoe@example.com',
        //     'osscei@example.com',
        //     'acu@example.com',
        //     'uoi@example.com',
        //     'lcui@example.com',
        //     'nouon@example.com',
        //     'tpi@example.com',
        //     'swipi@example.com',
        //     'tpi@example.com',
        //     'tpi@example.com',
        //     'bliceo@example.com',
        //     'fca@example.com',
        //     'fcapah@example.com',
        //     'fcea@example.com',
        //     'nasom@example.com',
        //     'nasn@example.com',
        //     'nij_nimc@example.com',
        //     'nisp_ikotun@example.com',
        //     'nls@example.com',
        //     'niit@example.com',
        //     'fcforestry@example.com',
        //     'mlcoeib@example.com',
        //     'osce@example.com',
        //     'sacoeoyo@example.com',
        //     'uoj@example.com',
        //     'psu@example.com',
        //     'psp@example.com',
        //     'ncajos@example.com',
        //     'caisr@example.com',
        //     'castk@example.com',
        //     'coej@example.com',
        //     'cohtz@example.com',
        //     'fcepan@example.com',
        //     'madonna@example.com',
        //     'nouon@example.com',
        //     'uoph@example.com',
        //     'rsut@example.com',
        //     'uosd@example.com',
        //     'rsp@example.com',
        //     'kccbug@example.com',
        //     'fceo@example.com',
        //     'coep@example.com',
        //     'rscarts@example.com',
        //     'rschst@example.com',
        //     'ssu@example.com',
        //     'nouon@example.com',
        //     'udu@example.com',
        //     'uduthson@example.com',
        //     'ssup@example.com',
        //     'hbcas@example.com',
        //     'stc@example.com',
        //     'tsu@example.com',
        //     'tarp@example.com',
        //     'tarp@example.com',
        //     'fstc@example.com',
        //     'tscar@example.com',
        //     'bagiu@example.com',
        //     'fpd@example.com',
        //     'cabspot@example.com',
        //     'coeg@example.com',
        //     'agg@example.com',
        //     'fpkn@example.com',
        //     'kkp@example.com',
        //     'cisg@example.com',
        //     'fug@example.com',
        //     'ntnu@example.com',
        //     'aust@example.com',
        //     'nouon@example.com'
        // ];

        // $new = [];
        // foreach ($old as $k) {
        //     $k = str_replace('@example.com', '@temp.com', $k);
        //     if (in_array($k, $new)) {
        //         $k = str_replace('@', rand(10, 99) . '@', $k);
        //     }
        //     if (in_array($k, $new)) {
        //         array_push(
        //             $new,
        //             str_replace('@', rand(10, 99) . '@', $k)
        //         );
        //     } else {
        //         array_push($new, $k);
        //     }
        // }


        // echo count($new) . '<br><br>';
        // foreach ($new as $k) {
        //     echo $k . '<br>';
        // }
        // return;


        if (Auth::user()) {
            if (Auth::user()->account_type == 'Student' && !Auth::user()->reg_completed) {
                return redirect()->intended('/' . account_type(Auth::user()->account_type) . '/reg/step/1');
            } elseif (Auth::user()->account_type == 'Admin' || Auth::user()->account_type == 'Student') {
                return redirect()->intended('/' . account_type(Auth::user()->account_type) . '/dashboard');
            }
        }

        return view('login');
    } // login


    public function reg_successful()
    {
        return view('register_done');
    } // reg_successful


    public function changePassword(Request $request, $email_base64, $token)
    {
        $is_present = PasswordReset::whereDate('expired_at', '>=', now())
            ->where('email', base64_decode($email_base64))
            ->where('token', $token)->count();

        if ($is_present < 1)
            return redirect('/login')->with('fail', 'The reset password link has expired or does not exist! Please generate a new link.');

        return view('change_password')->with([
            'email_base64' => $email_base64,
            'token' => $token
        ]);
    } // changePassword


    public function forgot_password()
    {
        return view('forgot_password');
    } // forgot_password


    public function sendVerificationLink()
    {
        return view('email_veri_link');
    } // sendVerificationLink
}
